
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 05 22:38:10 CET 2011
//----------------------------------------------------

package xi.parser;

/** CUP generated class containing symbol constants. */
@SuppressWarnings("all")
public class Terminal {
  /* terminals */
  public static final int SEQ = 17;
  public static final int CONS = 15;
  public static final int CHAR = 43;
  public static final int GE = 12;
  public static final int STR = 42;
  public static final int UMINUS = 19;
  public static final int SEMI = 34;
  public static final int MINUS = 3;
  public static final int NOT = 18;
  public static final int AND = 13;
  public static final int LT = 9;
  public static final int BRACE_R = 25;
  public static final int IN = 30;
  public static final int OR = 14;
  public static final int COMMA = 33;
  public static final int COMP = 36;
  public static final int DIV = 5;
  public static final int BRACE_L = 24;
  public static final int NUM = 38;
  public static final int PAR_R = 23;
  public static final int PLUS = 2;
  public static final int IF = 26;
  public static final int LE = 11;
  public static final int ELLIPSE = 37;
  public static final int EOF = 0;
  public static final int PAR_L = 22;
  public static final int APP = 16;
  public static final int error = 1;
  public static final int MOD = 6;
  public static final int EQ = 7;
  public static final int NAME = 40;
  public static final int BRACK_R = 21;
  public static final int FROM = 32;
  public static final int INAME = 41;
  public static final int TIMES = 4;
  public static final int BRACK_L = 20;
  public static final int ELSE = 28;
  public static final int BLN = 39;
  public static final int TO = 31;
  public static final int LET = 29;
  public static final int THEN = 27;
  public static final int NE = 8;
  public static final int DEF = 35;
  public static final int GT = 10;
}

