/* The following code was generated by JFlex 1.4.3 on 12.12.10 12:12 */

package xi.lexer;

import java_cup.runtime.Symbol;
import xi.parser.Terminal;
import static xi.util.StringUtils.*;

/*
 * WARNING: This file is auto generated! Do NOT edit this file!
 * Edit flex/subsasl.flex instead.
 */

@SuppressWarnings("all")

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12.12.10 12:12 from the specification file
 * <tt>D:/workspace/saslc/flex/subsasl.flex</tt>
 */
public final class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\32\1\20"+
    "\1\4\1\0\1\30\1\35\1\17\1\45\1\46\1\26\1\24\1\53"+
    "\1\25\1\41\1\27\12\5\1\37\1\54\1\33\1\31\1\34\1\0"+
    "\1\40\32\16\1\43\1\21\1\44\1\0\1\16\1\0\1\13\1\22"+
    "\2\16\1\11\1\12\1\16\1\52\1\51\2\16\1\14\1\16\1\23"+
    "\3\16\1\7\1\15\1\6\1\10\5\16\1\47\1\36\1\50\1\42"+
    "\77\0\1\16\17\0\1\16\uff31\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\3\2\1\3\5\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\4\1\32\1\33\5\4\5\0"+
    "\1\34\1\0\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\4\4\1\45\1\46\2\1\1\47\1\50"+
    "\1\51\2\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[70];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\55\0\207\0\264\0\341\0\u010e"+
    "\0\u013b\0\u0168\0\u0195\0\u01c2\0\u01ef\0\55\0\u021c\0\55"+
    "\0\55\0\55\0\u0249\0\u0276\0\u02a3\0\u02d0\0\55\0\55"+
    "\0\55\0\55\0\55\0\55\0\55\0\55\0\55\0\55"+
    "\0\55\0\55\0\u02fd\0\55\0\55\0\u032a\0\u0357\0\u0384"+
    "\0\u03b1\0\u03de\0\u040b\0\u0438\0\u0465\0\u01ef\0\u0492\0\55"+
    "\0\u04bf\0\55\0\55\0\55\0\55\0\55\0\55\0\u010e"+
    "\0\u010e\0\u04ec\0\u0519\0\u0546\0\u0573\0\u010e\0\55\0\u05a0"+
    "\0\u05cd\0\u010e\0\u010e\0\u010e\0\u05cd\0\u05fa";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[70];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\2\10\1\11"+
    "\1\12\1\10\1\13\2\10\1\14\1\15\1\2\2\10"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\10\1\44"+
    "\1\45\57\0\1\4\52\0\1\5\2\0\52\5\5\0"+
    "\1\6\54\0\2\10\1\46\10\10\2\0\2\10\25\0"+
    "\1\10\1\47\7\0\13\10\2\0\2\10\25\0\2\10"+
    "\7\0\7\10\1\50\3\10\2\0\2\10\25\0\2\10"+
    "\7\0\6\10\1\51\4\10\2\0\2\10\25\0\2\10"+
    "\7\0\4\10\1\52\6\10\2\0\2\10\25\0\2\10"+
    "\2\0\1\53\2\54\14\53\1\0\1\53\1\55\33\53"+
    "\1\56\2\57\15\56\1\60\1\61\33\56\34\0\1\62"+
    "\51\0\1\63\54\0\1\64\2\0\1\65\51\0\1\66"+
    "\54\0\1\67\30\0\5\10\1\70\5\10\2\0\1\10"+
    "\1\71\25\0\2\10\7\0\3\10\1\72\7\10\2\0"+
    "\2\10\25\0\2\10\7\0\4\10\1\73\6\10\2\0"+
    "\2\10\25\0\2\10\7\0\10\10\1\74\2\10\2\0"+
    "\2\10\25\0\2\10\7\0\7\10\1\75\3\10\2\0"+
    "\2\10\25\0\2\10\7\0\1\10\1\76\11\10\2\0"+
    "\2\10\25\0\2\10\2\0\17\54\1\77\54\54\1\2"+
    "\43\54\2\53\2\54\1\53\4\54\1\100\4\53\31\54"+
    "\20\57\1\2\42\57\2\56\2\57\1\56\4\57\1\56"+
    "\1\101\3\56\31\57\5\0\4\10\1\102\6\10\2\0"+
    "\2\10\25\0\2\10\7\0\13\10\2\0\1\10\1\103"+
    "\25\0\2\10\7\0\4\10\1\104\6\10\2\0\2\10"+
    "\25\0\2\10\7\0\10\10\1\72\2\10\2\0\2\10"+
    "\25\0\2\10\21\0\1\77\35\0\1\105\2\0\15\105"+
    "\1\60\1\106\33\105\6\0\2\105\2\0\1\105\4\0"+
    "\5\105\31\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1575];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\11\1\1\11\1\1\3\11"+
    "\4\1\14\11\1\1\2\11\5\1\5\0\1\11\1\0"+
    "\6\11\7\1\1\11\5\1\2\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[70];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

    // the symbol table - will be created when needed
    private static java.util.Map<Integer, String> symTable = null;

    /**
     * Gets the name of the given symbol.
     *
     * @param sym
     *            The symbols value.
     * @return The name of the symbol.
     */
    public static String getSymbolName(final int sym) {
    	if (sym == Terminal.error) {
			return "unrecognized token";
		}
        if (symTable == null) {
            symTable = new java.util.HashMap<Integer, String>();
            final java.lang.reflect.Field fs[] = Terminal.class.getFields();
            for (final java.lang.reflect.Field f : fs) {
                try {
                    symTable.put(f.getInt(null), f.getName());
                } catch (final Exception e) {
                    // ignore access restrictions...
                }
            }
        }
        return symTable.get(sym);
    }

	public static String getPrettySymbol(final Symbol s) {
		final String name = getSymbolName(s.sym);
		final Object value = s.value;
		return name + (value != null ? "[" + value.toString() + "]" : "");
	}

	public static String getPosition(final Symbol s) {
		return "line " + (s.left + 1) + " column " + (s.right + 1);
	}

	/**
	 * Runs the scanner on input files.
	 * 
	 * This main method is the debugging routine for the scanner. It prints
	 * debugging information about each returned token to System.out until the
	 * end of file is reached, or an error occured.
	 * 
	 * @param argv
	 *            the command line, contains the filenames to run the scanner
	 *            on.
	 */
	public static void main(final String argv[]) {
		if (argv.length == 0) {
			System.out.println("Usage : java Lexer <inputfile>");
			return;
		}
		for (final String element : argv) {
			Lexer scanner = null;
			try {
				scanner = new Lexer(new java.io.FileReader(element));
				while (!scanner.zzAtEOF) {
					final Symbol sym = scanner.next_token();
					System.out.println(getPrettySymbol(sym));
				}
			} catch (final java.io.FileNotFoundException e) {
				System.out.println("File not found : \"" + element + "\"");
			} catch (final java.io.IOException e) {
				System.out
						.println("IO error scanning file \"" + element + "\"");
				System.out.println(e);
			} catch (final Exception e) {
				System.out.println("Unexpected exception:");
				e.printStackTrace();
			}
		}
	}

	/*
	 * To create a new java_cup.runtime.Symbol with information about the
	 * current token, the token will have no value in this case.
	 */
	private Symbol symbol(final int type) {
		return new Symbol(type, yyline, yycolumn);
	}

    /*
     * Also creates a new java_cup.runtime.Symbol with information about the
     * current token, but this object has a value.
     */
    private Symbol symbol(final int type, final Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }
    


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { return symbol(Terminal.NAME, yytext());
          }
        case 42: break;
        case 33: 
          { return symbol(Terminal.LE);
          }
        case 43: break;
        case 3: 
          { return symbol(Terminal.NUM, Integer.valueOf(yytext()));
          }
        case 44: break;
        case 2: 
          { break;
          }
        case 45: break;
        case 29: 
          { return symbol(Terminal.TO);
          }
        case 46: break;
        case 6: 
          { return symbol(Terminal.MINUS);
          }
        case 47: break;
        case 23: 
          { return symbol(Terminal.PAR_R);
          }
        case 48: break;
        case 32: 
          { return symbol(Terminal.SEQ);
          }
        case 49: break;
        case 25: 
          { return symbol(Terminal.BRACE_R);
          }
        case 50: break;
        case 13: 
          { return symbol(Terminal.GT);
          }
        case 51: break;
        case 20: 
          { return symbol(Terminal.BRACK_L);
          }
        case 52: break;
        case 12: 
          { return symbol(Terminal.LT);
          }
        case 53: break;
        case 5: 
          { return symbol(Terminal.PLUS);
          }
        case 54: break;
        case 11: 
          { return symbol(Terminal.NOT);
          }
        case 55: break;
        case 14: 
          { return symbol(Terminal.AND);
          }
        case 56: break;
        case 26: 
          { return symbol(Terminal.COMMA);
          }
        case 57: break;
        case 8: 
          { return symbol(Terminal.DIV);
          }
        case 58: break;
        case 41: 
          { return symbol(Terminal.ELSE);
          }
        case 59: break;
        case 9: 
          { return symbol(Terminal.MOD);
          }
        case 60: break;
        case 28: 
          { return symbol(Terminal.STR, decode(yytext()));
          }
        case 61: break;
        case 40: 
          { return symbol(Terminal.THEN);
          }
        case 62: break;
        case 10: 
          { return symbol(Terminal.DEF);
          }
        case 63: break;
        case 21: 
          { return symbol(Terminal.BRACK_R);
          }
        case 64: break;
        case 19: 
          { return symbol(Terminal.UMINUS);
          }
        case 65: break;
        case 27: 
          { return symbol(Terminal.SEMI);
          }
        case 66: break;
        case 35: 
          { return symbol(Terminal.IF);
          }
        case 67: break;
        case 1: 
          { return symbol(Terminal.error, yytext());
          }
        case 68: break;
        case 38: 
          { return symbol(Terminal.CHAR, charDecode(yytext()));
          }
        case 69: break;
        case 17: 
          { return symbol(Terminal.APP);
          }
        case 70: break;
        case 37: 
          { return symbol(Terminal.LET);
          }
        case 71: break;
        case 36: 
          { return symbol(Terminal.IN);
          }
        case 72: break;
        case 15: 
          { return symbol(Terminal.OR);
          }
        case 73: break;
        case 30: 
          { return symbol(Terminal.EQ);
          }
        case 74: break;
        case 18: 
          { return symbol(Terminal.COMP);
          }
        case 75: break;
        case 31: 
          { return symbol(Terminal.NE);
          }
        case 76: break;
        case 22: 
          { return symbol(Terminal.PAR_L);
          }
        case 77: break;
        case 16: 
          { return symbol(Terminal.CONS);
          }
        case 78: break;
        case 7: 
          { return symbol(Terminal.TIMES);
          }
        case 79: break;
        case 24: 
          { return symbol(Terminal.BRACE_L);
          }
        case 80: break;
        case 39: 
          { return symbol(Terminal.BLN, Boolean.valueOf(yytext()));
          }
        case 81: break;
        case 34: 
          { return symbol(Terminal.GE);
          }
        case 82: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return symbol(Terminal.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
